### PR TITLE
header font size

### PR DESCRIPTION
**Pull request by marjan-tropper**
Increased header font size to 15 to match Ryan's design

### CODE REVIEW

**Comment by will0684** [comment]
Here are the global ionic themeing variables:
https://ionicframework.com/docs/theming/overriding-ionic-variables/

I believe the one for toolbar/navbar font size is:
iOS: $toolbar-ios-title-font-size
Android: $toolbar-md-title-font-size

**Comment by CalvinRodo** [comment]
I meant like make a sass variable for font size like `$headerFontSize : 15`

**Comment by marjan-tropper** [comment]
Calvin, the variables are not my variables. They are the built in variables for Ionic

**Comment by marjan-tropper** [comment]
They use different variables for each framework

**Comment by marjan-tropper** [comment]
They are sass variables

**Pull request merged**
