### PR TITLE
Questionnaire Nav Guard Implementation

### PR DESCRIPTION
**Pull request by will0684**
- Implemented Nav Guard
- Navigation out of question flow will prompt user to confirm
- Navbar back button within flow does not cause prompt to occur

### CODE REVIEW

**Comment by sdkibb** [comment]
@Clements-M Please review on device. Real one preferable but if not virtual will work too. Thanks.

**Comment by will0684** [comment]
Sorry may have put this through prematurely, going to close it, hopefully it's done by the end of the day. Have to fix a pretty big bug I just found.

**Comment by will0684** [comment]
Okay bugs should be mostly fixed. It isn't perfect but almost is. Still need to incorporate both translations.

**Comment by will0684** [comment]
Currently there is one issue related to what I'm trying to do:

- The "Previous Question" button pushes a new page onto the nav stack. This can work alright, but we currently have no checks to see what options had been previously selected by the user so the page is generated newly again. 

Besides this, I think this final commit should fix all the noticeable bugs that we're occurring before; Primarily with navigation by Previous Questions button causing context to believe it was exiting the Questionnaire flow and thus prompting the user. Please test and let me know what you guys think!

**Comment by will0684** [comment]
Prettier was removing escaped special characters in contextCheck() regex. Fixed issue by doubling escape character

**Comment by will0684** [comment]
@marjan-tropper just put through a seperate PR addressing those issues, anyone able to test and approve if working?

**Comment by will0684** [comment]
Added new translations based on design recently submitted by Fred. @marjan-tropper I think we should keep it consistent with platform design when it comes to this particular feature. It would be very jarring for an Android user to get a native iOS style alert. Currently the automatically generated component provides a better "native-like" user experience.

**Pull request merged**
