### PR TITLE
Menu Link Directs and MockStorage Changes

### PR DESCRIPTION
**Pull request by sdkibb**

### CODE REVIEW

**Comment by sdkibb** [comment]
Ok, it's ready.

**Comment by sdkibb** [comment]
@CalvinRodo I got all the properties in but you'll need to take a look at this when you're free to see what you think the best way to get around the new error is. I realize it may not be until next week which is fine. It's not critical right now. Error is: 

ERROR in ./src/pages/splash/splash.spec.ts
[tsl] ERROR in C:\sites\MTSApp\src\pages\splash\splash.spec.ts(28,27)
      TS2345: Argument of type 'StorageMock' is not assignable to parameter of type 'Storage'.
  Types have separate declarations of a private property '_dbPromise'.

#ae0fcd9

 I think it may need to be re-done from the way we're doing the overrides of the functions for the overridden object. In other words, I think we need to actually "extends" the super object but that's a substantial change so want you to look at it.

**Comment by sdkibb** [comment]
@CalvinRodo @will0684 When you get a chance please review approve so I can push this to master. I no longer have the power of the override (as far as I can tell).

Thanks.

**Comment by will0684** [comment]
@sdkibb Kk I'll take a look when I get home either today or tomorrow no problem.

**Comment by CalvinRodo** [comment]
I didn't mean to turn off admin rights to push to master but I will approve

**Comment by CalvinRodo** [comment]
Pushing it through

**Pull request merged**
