### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by CalvinRodo**
Added Validation for Controls on the EI Login page.

### CODE REVIEW

**Comment by CalvinRodo** [comment]
It might just be that your dependencies aren't being automatically updated on ionic serve. I'll have to look if that's expected or if we have to do `npm i` when pulling in new deps.

**Comment by sdkibb** [comment]
OK. It happened on build as well as serve. nmp i was going to be my next try but didn't want to presume. I can just run it and see but then we have instructions to nmp i going forward on new module changes. Which I guess might be standard practice for these types of errors.

**Comment by CalvinRodo** [comment]
I think this is just learning the ins and out of node programming. I'll read up on it tonight and figure out the workflow for adding deps.

**Comment by sdkibb** [comment]
npm i appears to have worked.
Validation with "you suck" successful. 
I say we send this through and know that npm i is required if you get that error going forward.

**Pull request merged**
